### ISSUE TITLE
ClassNotFoundException using hystrix starter

### ISSUE THREAD

**Issue by moritzzimmer** [spring-cloud/spring-cloud-starters#20]
We are using the **org.springframework.cloud:spring-cloud-starter-hystrix:1.0.3.RELEASE** dependency in our **gradle 2.4** project with **org.springframework.boot:spring-boot-gradle-plugin:1.3.0.M1**. Starting the boot projects results in:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.netflix.archaius.ConfigurableEnvironmentConfiguration]: Circular reference involving containing bean 'org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'configurableEnvironmentConfiguration' threw exception; nested exception is java.lang.NoClassDefFoundError: com/netflix/config/DeploymentContext$ContextKey
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 34 more
Caused by: java.lang.NoClassDefFoundError: com/netflix/config/DeploymentContext$ContextKey
	at org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration.configureArchaius(ArchaiusAutoConfiguration.java:133)
	at org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration.configurableEnvironmentConfiguration(ArchaiusAutoConfiguration.java:88)
	at org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration$$EnhancerBySpringCGLIB$$481cd061.CGLIB$configurableEnvironmentConfiguration$1(<generated>)
	at org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration$$EnhancerBySpringCGLIB$$481cd061$$FastClassBySpringCGLIB$$bed9a7a1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:312)
	at org.springframework.cloud.netflix.archaius.ArchaiusAutoConfiguration$$EnhancerBySpringCGLIB$$481cd061.configurableEnvironmentConfiguration(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 35 more
Caused by: java.lang.ClassNotFoundException: com.netflix.config.DeploymentContext$ContextKey
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
```

It seems like that the **archaius-core:0.4.1** (see dependency tree below) jar doesn't include this class file:
```
+--- org.springframework.cloud:spring-cloud-starter-hystrix: -> 1.0.3.RELEASE
|    ...
|    +--- com.netflix.hystrix:hystrix-core:1.4.10
|    |    +--- com.netflix.archaius:archaius-core:0.4.1
```

As a workaround we explicitly enforce a newer version of that lib using the dependency management plugin which fixes the problem:
```groovy
dependency 'com.netflix.archaius:archaius-core:0.7.1'
```

Any ideas?

**Comment by dsyer** [comment]
If you are using gradle you probably want the dependency management plugin as well (or the Spring Boot plugin in 1.3): https://github.com/spring-gradle-plugins/dependency-management-plugin. If you generate a project from https://start.spring.io it will have the correct dependencies I think.

**Comment by francoisledroff** [comment]
I faced the same issue, my work-around was to upgradre archaius as well, and use the following maven dependencies:

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix</artifactId>
            <version>1.0.3.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>om.netflix.archaius</groupId>
                    <artifactId>archaius-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>com.netflix.archaius</groupId>
            <artifactId>archaius-core</artifactId>
            <version>0.7.1</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-hystrix-dashboard</artifactId>
            <version>1.0.3.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>om.netflix.archaius</groupId>
                    <artifactId>archaius-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by lesongjia** [comment]
I have the same issue using gradle. Is there an update rather than the workaround? Thanks

**Comment by dsyer** [comment]
Using the dependency management plugin is not a workaround. AFAIK that will work for everyone.

**Comment by lesongjia** [comment]
Thanks for your clarification, dsyer.
