### ISSUE TITLE
OAuth Error using Brixton.BUILD-SNAPSHOT 

### ISSUE THREAD

**Issue by victor-ferrer** [spring-cloud/spring-cloud-starters#28]
Not sure if I should report a bug on a BUILD SNAPSHOT but I get this error using the latest (as of 21st October 2015) SNAPSHOT of the Spring Cloud Starter:

>2015-10-21 15:36:35.023 DEBUG 5624 --- [nio-9999-exec-8] uth2ClientAuthenticationProcessingFilter : Request is to process authentication
>2015-10-21 15:36:35.024 DEBUG 5624 --- [nio-9999-exec-8] w.c.HttpSessionSecurityContextRepository : SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
>2015-10-21 15:36:35.024 DEBUG 5624 --- [nio-9999-exec-8] s.s.w.c.SecurityContextPersistenceFilter : SecurityContextHolder now cleared, as request processing completed
>2015-10-21 15:36:35.026 ERROR 5624 --- [nio-9999-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) ~[spring-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.web.context.request.SessionScope.get(SessionScope.java:91) ~[spring-web-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:339) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	... 64 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.oauth2ClientContext': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet/DispatcherPortlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:354) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:196) ~[spring-beans-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) ~[spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:187) ~[spring-aop-4.2.1.RELEASE.jar:4.2.1.RELEASE]
	at com.sun.proxy.$Proxy112.getAccessToken(Unknown Source) ~[na:na]

Note that this warning appears in the failed execution:

> 2015-10-21 15:36:12.272  INFO 5624 --- [ost-startStop-1] o.s.aop.framework.CglibAopProxy          : Unable to proxy method [protected final org.springframework.security.config.annotation.web.builders.HttpSecurity org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.getHttp() throws java.lang.Exception] because it is final: All calls to this method via a proxy will NOT be routed to the target instance.

However, if I downgrade to Brixton.M1 this error disappears. I´m attaching both execution logs, let me know if you need more info.

**Comment by victor-ferrer** [comment]
I don´t have access to the repository, so I can´t upload the trace files.

**Comment by spencergibb** [comment]
Not sure this has anything to do with the starters per se, more likely has to do with the version of boot.

**Comment by spencergibb** [comment]
Closing, if this is still a problem, open an issue in spring-cloud-security.
